apiVersion: v1
kind: Service
metadata:
  name: mafia-backend-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mafia
    name: mafia-backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.targetPort }}

