apiVersion: v1
kind: Service
metadata:
  name: mafia-ui-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: mafia
    name: mafia-ui
  ports:
    - protocol: TCP
      port: {{ .Values.ui.port }}
      targetPort: {{ .Values.ui.targetPort }}

