apiVersion: apps/v1
kind: Deployment
metadata:
  name: mafia-backend
  namespace: mafia
  labels:
    name: mafia-backend
    app: mafia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mafia
  template:
    metadata:
      labels:
        name: mafia-backend
        app: mafia
    spec:
      containers:
      - name: mafia-backend-container
        image: taleodor/mafia-express@sha256:c71421b70491525e7ffbc72c8007b30fbb5068d791f595005dac1f46986d6713
        env:
        - name: REDIS_HOST
          value: redis-service.mafia
        ports:
        - containerPort: 3000
