apiVersion: apps/v1
kind: Deployment
metadata:
  name: mafia-backend
  namespace: mafia
  labels:
    name: mafia-backend
    app: mafia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mafia
  template:
    metadata:
      labels:
        name: mafia-backend
        app: mafia
    spec:
      containers:
      - name: mafia-backend-container
        image: taleodor/mafia-express@sha256:6de2fc694a66e8322decb2064c417ddd110950540e38219720f7f10f886db87a
        env:
        - name: REDIS_HOST
          value: redis-service.mafia
        ports:
        - containerPort: 3000
