apiVersion: apps/v1
kind: Deployment
metadata:
  name: mafia-backend
  namespace: mafia
  labels:
    name: mafia-backend
    app: mafia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mafia
  template:
    metadata:
      labels:
        name: mafia-backend
        app: mafia
    spec:
      containers:
      - name: mafia-backend-container
        image: taleodor/mafia-express@sha256:c842628e75c069e5edf55853a32e8f17b0f2df2a7212c6f69241a61d4a5c245a
        env:
        - name: REDIS_HOST
          value: redis-service.mafia
        ports:
        - containerPort: 3000
