apiVersion: apps/v1
kind: Deployment
metadata:
  name: mafia-backend
  namespace: mafia
  labels:
    name: mafia-backend
    app: mafia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mafia
  template:
    metadata:
      labels:
        name: mafia-backend
        app: mafia
    spec:
      containers:
      - name: mafia-backend-container
        image: taleodor/mafia-express@sha256:9750c70b8d525c00397732eb7274bd8bb6e7d236f4a9c6c2dc0453663fb48ca2
        env:
        - name: REDIS_HOST
          value: redis-service.mafia
        ports:
        - containerPort: 3000
