apiVersion: apps/v1
kind: Deployment
metadata:
  name: mafia-ui
  namespace: mafia
  labels:
    name: mafia-ui
    app: mafia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mafia
  template:
    metadata:
      labels:
        name: mafia-ui
        app: mafia
    spec:
      containers:
      - name: mafia-ui-container
        image: taleodor/mafia-vue@sha256:3eab69ed34fb56855e29f55fb017457120c480106e6da8caa1b639474c35b057
        env:
        - name: HUB_HOST
          value: mafia-backend-service.mafia
        - name: HUB_PORT
          value: "3000"
        ports:
        - containerPort: 80
