apiVersion: apps/v1
kind: Deployment
metadata:
  name: mafia-ui
  namespace: mafia
  labels:
    name: mafia-ui
    app: mafia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mafia
  template:
    metadata:
      labels:
        name: mafia-ui
        app: mafia
    spec:
      containers:
      - name: mafia-ui-container
        image: taleodor/mafia-vue@sha256:e6e0789e9cf15c81961242c503fafa2e10e5313de678499f84708ba80eca13ec
        env:
        - name: HUB_HOST
          value: mafia-backend-service.mafia
        - name: HUB_PORT
          value: "3000"
        ports:
        - containerPort: 80
