namespace: mafia
backend:
  image: taleodor/mafia-express:latest
  replicaCount: 1
  port: 3000
  targetPort: 3000
ui:
  image: taleodor/mafia-vue:latest
  replicaCount: 1
  port: 80
  targetPort: 80
ingress:
  nginxEnabled: false
  traefikEnabled: false
  host: mafia.brolia.com