namespace: mafia
backend:
  image: registry.gitlab.com/mafia5/mafia-express:latest
  replicaCount: 1
  port: 3000
  targetPort: 3000
ui:
  image: registry.gitlab.com/mafia5/mafia-vue:latest
  replicaCount: 1
  port: 80
  targetPort: 80
ingress:
  nginxEnabled: false
  traefikEnabled: true
  host: mafia.rhythm.relizahub.com