apiVersion: apps/v1
kind: Deployment
metadata:
  name: mafia-ui
  namespace: mafia
  labels:
    name: mafia-ui
    app: mafia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mafia
  template:
    metadata:
      labels:
        name: mafia-ui
        app: mafia
    spec:
      containers:
      - name: mafia-ui-container
        image: <%PROJECT__55fe88fc-5621-4c90-b006-db94ea1d8a08__master%>
        env:
        - name: HUB_HOST
          value: mafia-backend-service.mafia
        - name: HUB_PORT
          value: "3000"
        ports:
        - containerPort: 80
