on: [push]

name: Obtain version from Reliza and register new update there

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate version and stream version to Reliza Hub
        run: |
          # get version
          docker pull relizaio/reliza-cli
          docker run --rm relizaio/reliza-cli getversion -k ${{ secrets.RELIZA_API_KEY }} -i ${{ secrets.RELIZA_API_ID }} -b $GITHUB_REF --metadata GitHub > full_version_output 2>&1
          # show reliza command output in case there is error
          cat full_version_output
          cat full_version_output | jq -r ".version" > version
          vvar=$(cat version)
          # Construct Reliza command to stream version to reliza
          echo -n "--artid github.com/$GITHUB_REPOSITORY " >> reliza_command
          echo -n "--artbuildid github$GITHUB_ACTION$GITHUB_SHA " >> reliza_command
          echo -n "--artbuilduri https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID " >> reliza_command
          echo -n "--artcimeta GitHub Actions " >> reliza_command
          echo -n "--arttype file " >> reliza_command
          echo -n "--artdigests sha1:$GITHUB_SHA " >> reliza_command
          echo -n "-b $GITHUB_REF --vcstype git --commit $GITHUB_SHA --commitmessage "$(git log -1 --pretty='%s')" \
            -k ${{ secrets.RELIZA_API_KEY }} -i ${{ secrets.RELIZA_API_ID }} --vcsuri github.com/$GITHUB_REPOSITORY \
            -v $vvar" >> reliza_command
          # extract last release commit and prepare list of commits
          last_commit=$(docker run --rm relizaio/reliza-cli getlatestrelease -i ${{ secrets.RELIZA_API_ID }} -k ${{ secrets.RELIZA_API_KEY }} --branch $GITHUB_REF | jq -r ".sourceCodeEntryDetails.commit")
          if [ ! -z "$last_commit" ]
          then
            echo -n "--commits $(git log $last_commit..$GITHUB_SHA --date=iso-strict --pretty='%H|||%ad|||%s' | base64 -w 0) " >> reliza_command
          fi
          cat reliza_command
          # send version to reliza
          docker run --rm relizaio/reliza-cli addrelease $(cat reliza_command)